// <auto-generated />
#pragma warning disable CS8618

namespace NexusServices
{
    using NexusRpc;
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// An inventory tracking service that demonstrates using $langRef to reference types that
    /// already exist in your target language instead of generating new ones.
    /// </summary>
    [NexusService]
    public interface IInventoryService
    {
        /// <summary>
        /// Add a new item to the inventory.
        /// </summary>
        [NexusOperation("addItem")]
        Example.Inventory.AddItemOutput AddItem(Example.Inventory.AddItemInput input);

        /// <summary>
        /// Get current stock levels for an item.
        /// </summary>
        [NexusOperation("getItemStock")]
        Example.Inventory.StockLevel GetItemStock(Example.Inventory.StockQuery input);

        /// <summary>
        /// Reserve stock for a pending order.
        /// </summary>
        [NexusOperation("reserveStock")]
        Example.Inventory.ReservationResult ReserveStock(Example.Inventory.ReservationRequest input);
    }
}
