// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.io.IOException;

public enum Action {
  CREATED,
  UPDATED;

  @JsonValue
  public String toValue() {
    switch (this) {
      case CREATED:
        return "created";
      case UPDATED:
        return "updated";
    }
    return null;
  }

  @JsonCreator
  public static Action forValue(String value) throws IOException {
    if (value.equals("created")) return CREATED;
    if (value.equals("updated")) return UPDATED;
    throw new IOException("Cannot deserialize Action");
  }
}
