// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.annotation.*;
import java.io.IOException;

@JsonDeserialize(using = Actor.Deserializer.class)
@JsonSerialize(using = Actor.Serializer.class)
public class Actor {
  public Long integerValue;
  public String stringValue;

  static class Deserializer extends JsonDeserializer<Actor> {
    @Override
    public Actor deserialize(JsonParser jsonParser, DeserializationContext deserializationContext)
        throws IOException, JsonProcessingException {
      Actor value = new Actor();
      switch (jsonParser.currentToken()) {
        case VALUE_NUMBER_INT:
          value.integerValue = jsonParser.readValueAs(Long.class);
          break;
        case VALUE_STRING:
          String string = jsonParser.readValueAs(String.class);
          value.stringValue = string;
          break;
        default:
          throw new IOException("Cannot deserialize Actor");
      }
      return value;
    }
  }

  static class Serializer extends JsonSerializer<Actor> {
    @Override
    public void serialize(
        Actor obj, JsonGenerator jsonGenerator, SerializerProvider serializerProvider)
        throws IOException {
      if (obj.integerValue != null) {
        jsonGenerator.writeObject(obj.integerValue);
        return;
      }
      if (obj.stringValue != null) {
        jsonGenerator.writeObject(obj.stringValue);
        return;
      }
      throw new IOException("Actor must not be null");
    }
  }
}
