// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.io.IOException;

public enum Breed {
  HERDING,
  HOUND,
  WORKING;

  @JsonValue
  public String toValue() {
    switch (this) {
      case HERDING:
        return "herding";
      case HOUND:
        return "hound";
      case WORKING:
        return "working";
    }
    return null;
  }

  @JsonCreator
  public static Breed forValue(String value) throws IOException {
    if (value.equals("herding")) return HERDING;
    if (value.equals("hound")) return HOUND;
    if (value.equals("working")) return WORKING;
    throw new IOException("Cannot deserialize Breed");
  }
}
