// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class Cat {
  private Boolean hunts;
  private Kind kind;
  private Breed breed;

  @JsonProperty("hunts")
  public Boolean getHunts() {
    return hunts;
  }

  @JsonProperty("hunts")
  public void setHunts(Boolean value) {
    this.hunts = value;
  }

  @JsonProperty("kind")
  public Kind getKind() {
    return kind;
  }

  @JsonProperty("kind")
  public void setKind(Kind value) {
    this.kind = value;
  }

  @JsonProperty("breed")
  public Breed getBreed() {
    return breed;
  }

  @JsonProperty("breed")
  public void setBreed(Breed value) {
    this.breed = value;
  }
}
