// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.io.IOException;

public enum FixedKind {
  PAYLOAD;

  @JsonValue
  public String toValue() {
    switch (this) {
      case PAYLOAD:
        return "payload";
    }
    return null;
  }

  @JsonCreator
  public static FixedKind forValue(String value) throws IOException {
    if (value.equals("payload")) return PAYLOAD;
    throw new IOException("Cannot deserialize FixedKind");
  }
}
