// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.time.OffsetDateTime;

public class HistoryEvent {
  private Action action;
  private Actor actor;
  private OffsetDateTime at;

  @JsonProperty("action")
  public Action getAction() {
    return action;
  }

  @JsonProperty("action")
  public void setAction(Action value) {
    this.action = value;
  }

  @JsonProperty("actor")
  public Actor getActor() {
    return actor;
  }

  @JsonProperty("actor")
  public void setActor(Actor value) {
    this.actor = value;
  }

  @JsonProperty("at")
  public OffsetDateTime getAt() {
    return at;
  }

  @JsonProperty("at")
  public void setAt(OffsetDateTime value) {
    this.at = value;
  }
}
