// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.time.OffsetDateTime;
import java.util.Map;

/** A payload intended to exercise many JSON Schema features. */
public class JSONSchemaFeaturesPayload {
  private boolean active;
  private ShippingAddress address;
  private PrimaryContact contact;
  private long count;
  private FixedKind fixedKind;
  private HistoryEvent[] history;
  private String id;
  private Manager manager;
  private Map<String, String> metadata;
  private String nullableNote;
  private Cat pet;
  private double price;
  private double[][] scoreMatrix;
  private Status status;
  private String[] tags;
  private OffsetDateTime timestamp;
  private Actor variant;

  @JsonProperty("active")
  public boolean getActive() {
    return active;
  }

  @JsonProperty("active")
  public void setActive(boolean value) {
    this.active = value;
  }

  @JsonProperty("address")
  public ShippingAddress getAddress() {
    return address;
  }

  @JsonProperty("address")
  public void setAddress(ShippingAddress value) {
    this.address = value;
  }

  @JsonProperty("contact")
  public PrimaryContact getContact() {
    return contact;
  }

  @JsonProperty("contact")
  public void setContact(PrimaryContact value) {
    this.contact = value;
  }

  @JsonProperty("count")
  public long getCount() {
    return count;
  }

  @JsonProperty("count")
  public void setCount(long value) {
    this.count = value;
  }

  @JsonProperty("fixedKind")
  public FixedKind getFixedKind() {
    return fixedKind;
  }

  @JsonProperty("fixedKind")
  public void setFixedKind(FixedKind value) {
    this.fixedKind = value;
  }

  @JsonProperty("history")
  public HistoryEvent[] getHistory() {
    return history;
  }

  @JsonProperty("history")
  public void setHistory(HistoryEvent[] value) {
    this.history = value;
  }

  @JsonProperty("id")
  public String getID() {
    return id;
  }

  @JsonProperty("id")
  public void setID(String value) {
    this.id = value;
  }

  @JsonProperty("manager")
  public Manager getManager() {
    return manager;
  }

  @JsonProperty("manager")
  public void setManager(Manager value) {
    this.manager = value;
  }

  @JsonProperty("metadata")
  public Map<String, String> getMetadata() {
    return metadata;
  }

  @JsonProperty("metadata")
  public void setMetadata(Map<String, String> value) {
    this.metadata = value;
  }

  @JsonProperty("nullableNote")
  public String getNullableNote() {
    return nullableNote;
  }

  @JsonProperty("nullableNote")
  public void setNullableNote(String value) {
    this.nullableNote = value;
  }

  @JsonProperty("pet")
  public Cat getPet() {
    return pet;
  }

  @JsonProperty("pet")
  public void setPet(Cat value) {
    this.pet = value;
  }

  @JsonProperty("price")
  public double getPrice() {
    return price;
  }

  @JsonProperty("price")
  public void setPrice(double value) {
    this.price = value;
  }

  @JsonProperty("scoreMatrix")
  public double[][] getScoreMatrix() {
    return scoreMatrix;
  }

  @JsonProperty("scoreMatrix")
  public void setScoreMatrix(double[][] value) {
    this.scoreMatrix = value;
  }

  @JsonProperty("status")
  public Status getStatus() {
    return status;
  }

  @JsonProperty("status")
  public void setStatus(Status value) {
    this.status = value;
  }

  @JsonProperty("tags")
  public String[] getTags() {
    return tags;
  }

  @JsonProperty("tags")
  public void setTags(String[] value) {
    this.tags = value;
  }

  @JsonProperty("timestamp")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  @JsonProperty("timestamp")
  public void setTimestamp(OffsetDateTime value) {
    this.timestamp = value;
  }

  @JsonProperty("variant")
  public Actor getVariant() {
    return variant;
  }

  @JsonProperty("variant")
  public void setVariant(Actor value) {
    this.variant = value;
  }
}
