// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;

/** Exercises a broad set of JSON Schema features. */
@Service(name = "JsonSchemaFeaturesService")
public interface JSONSchemaFeaturesService {
  @Operation
  JSONSchemaFeaturesPayload roundTrip(JSONSchemaFeaturesPayload input);
}
