// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.io.IOException;

public enum Kind {
  CAT,
  DOG;

  @JsonValue
  public String toValue() {
    switch (this) {
      case CAT:
        return "cat";
      case DOG:
        return "dog";
    }
    return null;
  }

  @JsonCreator
  public static Kind forValue(String value) throws IOException {
    if (value.equals("cat")) return CAT;
    if (value.equals("dog")) return DOG;
    throw new IOException("Cannot deserialize Kind");
  }
}
