// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;

/** A service for all types of operations */
@Service
public interface KitchenSinkService {
  /** Counts the characters in the string */
  @Operation
  long scalarArgScalarResult(String input);

  /** Counts the characters in a string */
  @Operation
  KitchenSinkServiceComplexArgComplexResultInlineOutput complexArgComplexResultInline(
      KitchenSinkServiceComplexArgComplexResultInlineInput input);

  @Operation
  long scalarArgScalarResultExternal(String input);

  @Operation
  ComplexOutput complexArgComplexResultExternal(ComplexInput input);
}
