// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class Manager {
  private String email;
  private String name;
  private String department;
  private Long reports;

  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  @JsonProperty("email")
  public void setEmail(String value) {
    this.email = value;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("name")
  public void setName(String value) {
    this.name = value;
  }

  @JsonProperty("department")
  public String getDepartment() {
    return department;
  }

  @JsonProperty("department")
  public void setDepartment(String value) {
    this.department = value;
  }

  @JsonProperty("reports")
  public Long getReports() {
    return reports;
  }

  @JsonProperty("reports")
  public void setReports(Long value) {
    this.reports = value;
  }
}
