// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.io.IOException;

public enum Method {
  EMAIL;

  @JsonValue
  public String toValue() {
    switch (this) {
      case EMAIL:
        return "email";
    }
    return null;
  }

  @JsonCreator
  public static Method forValue(String value) throws IOException {
    if (value.equals("email")) return EMAIL;
    throw new IOException("Cannot deserialize Method");
  }
}
