// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class PrimaryContact {
  private String email;
  private Method method;

  @JsonProperty("email")
  public String getEmail() {
    return email;
  }

  @JsonProperty("email")
  public void setEmail(String value) {
    this.email = value;
  }

  @JsonProperty("method")
  public Method getMethod() {
    return method;
  }

  @JsonProperty("method")
  public void setMethod(Method value) {
    this.method = value;
  }
}
