// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.util.Map;

public class RequiredCollectionsInput {
  private Map<String, String> metadata;
  private long[] optionalList;
  private String[] tags;

  @JsonProperty("metadata")
  public Map<String, String> getMetadata() { return metadata; }
  @JsonProperty("metadata")
  public void setMetadata(Map<String, String> value) { this.metadata = value; }

  @JsonProperty("optionalList")
  public long[] getOptionalList() { return optionalList; }
  @JsonProperty("optionalList")
  public void setOptionalList(long[] value) { this.optionalList = value; }

  @JsonProperty("tags")
  public String[] getTags() { return tags; }
  @JsonProperty("tags")
  public void setTags(String[] value) { this.tags = value; }
}
