// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class RequiredCollectionsOutput {
  private String[] items;

  @JsonProperty("items")
  public String[] getItems() { return items; }
  @JsonProperty("items")
  public void setItems(String[] value) { this.items = value; }
}
