// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;

@Service
public interface ReservedWordService {
  @Operation(name = "ToString")
  void toStringOperation();
}
