// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class SharedObject {
  private Long someField;

  @JsonProperty("someField")
  public Long getSomeField() {
    return someField;
  }

  @JsonProperty("someField")
  public void setSomeField(Long value) {
    this.someField = value;
  }
}
