// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class ShippingAddress {
  private String city;
  private String countryCode;
  private String line1;
  private String postalCode;
  private String instructions;
  private boolean residential;

  @JsonProperty("city")
  public String getCity() {
    return city;
  }

  @JsonProperty("city")
  public void setCity(String value) {
    this.city = value;
  }

  @JsonProperty("countryCode")
  public String getCountryCode() {
    return countryCode;
  }

  @JsonProperty("countryCode")
  public void setCountryCode(String value) {
    this.countryCode = value;
  }

  @JsonProperty("line1")
  public String getLine1() {
    return line1;
  }

  @JsonProperty("line1")
  public void setLine1(String value) {
    this.line1 = value;
  }

  @JsonProperty("postalCode")
  public String getPostalCode() {
    return postalCode;
  }

  @JsonProperty("postalCode")
  public void setPostalCode(String value) {
    this.postalCode = value;
  }

  @JsonProperty("instructions")
  public String getInstructions() {
    return instructions;
  }

  @JsonProperty("instructions")
  public void setInstructions(String value) {
    this.instructions = value;
  }

  @JsonProperty("residential")
  public boolean getResidential() {
    return residential;
  }

  @JsonProperty("residential")
  public void setResidential(boolean value) {
    this.residential = value;
  }
}
