// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;
import java.io.IOException;

public enum Status {
  ACTIVE,
  DISABLED,
  PENDING;

  @JsonValue
  public String toValue() {
    switch (this) {
      case ACTIVE:
        return "active";
      case DISABLED:
        return "disabled";
      case PENDING:
        return "pending";
    }
    return null;
  }

  @JsonCreator
  public static Status forValue(String value) throws IOException {
    if (value.equals("active")) return ACTIVE;
    if (value.equals("disabled")) return DISABLED;
    if (value.equals("pending")) return PENDING;
    throw new IOException("Cannot deserialize Status");
  }
}
