// Generated by nexus-rpc-gen. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import { type AddItemInput, type AddItemOutput, type GetItemStockOutput } from "./types.js";

/**
 * An inventory tracking service that demonstrates using $langRef to reference types that
 * already exist in your target language instead of generating new ones.
 */
export const inventoryService = nexus.service("InventoryService", {
  /**
   * Add a new item to the inventory.
   */
  addItem: nexus.operation<AddItemInput, AddItemOutput>(),

  /**
   * Get current stock levels for an item.
   */
  getItemStock: nexus.operation<GetItemStockInput, GetItemStockOutput>(),

  /**
   * Reserve stock for a pending order.
   */
  reserveStock: nexus.operation<ReserveStockInput, ReserveStockOutput>(),
});

export interface GetItemStockInput {
  /**
   * The SKU to look up.
   */
  sku: string;
}

export interface ReserveStockInput {
  /**
   * The order this reservation is for.
   */
  orderId: string;
  /**
   * Number of units to reserve.
   */
  quantity: number;
  /**
   * The SKU to reserve.
   */
  sku: string;
}

export interface ReserveStockOutput {
  /**
   * Whether the stock was successfully reserved.
   */
  reserved: boolean;
}
