// <auto-generated />
#pragma warning disable CS8618

namespace NexusServices
{
    using NexusRpc;
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// An inventory tracking service that demonstrates using $langRef to reference types that
    /// already exist in your target language instead of generating new ones.
    /// </summary>
    [NexusService]
    public interface IInventoryService
    {
        /// <summary>
        /// Add a new item to the inventory.
        /// </summary>
        [NexusOperation("addItem")]
        Example.Inventory.AddItemOutput AddItem(Example.Inventory.AddItemInput input);

        /// <summary>
        /// Get current stock levels for an item.
        /// </summary>
        [NexusOperation("getItemStock")]
        Example.Inventory.GetItemStockOutput GetItemStock(GetItemStockInput input);

        /// <summary>
        /// Reserve stock for a pending order.
        /// </summary>
        [NexusOperation("reserveStock")]
        ReserveStockOutput ReserveStock(ReserveStockInput input);
    }

    public partial class GetItemStockInput
    {
        /// <summary>
        /// The SKU to look up.
        /// </summary>
        [JsonPropertyName("sku")]
        public string Sku { get; set; }
    }

    public partial class ReserveStockInput
    {
        /// <summary>
        /// The order this reservation is for.
        /// </summary>
        [JsonPropertyName("orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// Number of units to reserve.
        /// </summary>
        [JsonPropertyName("quantity")]
        public long Quantity { get; set; }

        /// <summary>
        /// The SKU to reserve.
        /// </summary>
        [JsonPropertyName("sku")]
        public string Sku { get; set; }
    }

    public partial class ReserveStockOutput
    {
        /// <summary>
        /// Whether the stock was successfully reserved.
        /// </summary>
        [JsonPropertyName("reserved")]
        public bool Reserved { get; set; }
    }
}
