# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import service, Operation
from pydantic import BaseModel, model_validator
from typing import Any, get_origin
import inventory.types


class _NexusBase(BaseModel):
    @model_validator(mode="before")
    @classmethod
    def _coerce_null_lists(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for name, field in cls.model_fields.items():
                if get_origin(field.annotation) is list:
                    key = field.alias or name
                    if key in data and data[key] is None:
                        data[key] = []
                    elif name in data and data[name] is None:
                        data[name] = []
        return data


@service
class InventoryService:
    """An inventory tracking service that demonstrates using $langRef to reference types that
    already exist in your target language instead of generating new ones.
    """
    add_item: Operation[inventory.types.AddItemInput, inventory.types.AddItemOutput] = Operation(name="addItem")
    """Add a new item to the inventory."""

    get_item_stock: Operation[inventory.types.StockQuery, inventory.types.StockLevel] = Operation(name="getItemStock")
    """Get current stock levels for an item."""

    reserve_stock: Operation[inventory.types.ReservationRequest, inventory.types.ReservationResult] = Operation(name="reserveStock")
    """Reserve stock for a pending order."""
