# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from nexusrpc import service, Operation
import inventory.types


@service
class InventoryService:
    """An inventory tracking service that demonstrates using $langRef to reference types that
    already exist in your target language instead of generating new ones.
    """
    add_item: Operation[inventory.types.AddItemInput, inventory.types.AddItemOutput] = Operation(name="addItem")
    """Add a new item to the inventory."""

    get_item_stock: Operation[inventory.types.StockQuery, inventory.types.StockLevel] = Operation(name="getItemStock")
    """Get current stock levels for an item."""

    reserve_stock: Operation[inventory.types.ReservationRequest, inventory.types.ReservationResult] = Operation(name="reserveStock")
    """Reserve stock for a pending order."""
