// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class AddItemInput {
  private long initialQuantity;
  private String name;
  private String sku;

  /**
   * Starting quantity to stock.
   */
  @JsonProperty("initialQuantity")
  public long getInitialQuantity() { return initialQuantity; }
  @JsonProperty("initialQuantity")
  public void setInitialQuantity(long value) { this.initialQuantity = value; }

  /**
   * Human-readable item name.
   */
  @JsonProperty("name")
  public String getName() { return name; }
  @JsonProperty("name")
  public void setName(String value) { this.name = value; }

  /**
   * Stock-keeping unit identifier.
   */
  @JsonProperty("sku")
  public String getSku() { return sku; }
  @JsonProperty("sku")
  public void setSku(String value) { this.sku = value; }
}
