// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class AddItemOutput {
  private boolean added;

  /**
   * Whether the item was successfully added.
   */
  @JsonProperty("added")
  public boolean getAdded() { return added; }
  @JsonProperty("added")
  public void setAdded(boolean value) { this.added = value; }
}
