// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class GetItemStockInput {
  private String sku;

  /**
   * The SKU to look up.
   */
  @JsonProperty("sku")
  public String getSku() { return sku; }
  @JsonProperty("sku")
  public void setSku(String value) { this.sku = value; }
}
