// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import io.nexusrpc.Operation;
import io.nexusrpc.Service;

/**
 * An inventory tracking service that demonstrates using $langRef to reference types that
 * already exist in your target language instead of generating new ones.
 */
@Service
public interface InventoryService {
  /**
   * Add a new item to the inventory.
   */
  @Operation
  com.example.inventory.AddItemOutput addItem(com.example.inventory.AddItemInput input);

  /**
   * Get current stock levels for an item.
   */
  @Operation
  com.example.inventory.GetItemStockOutput getItemStock(GetItemStockInput input);

  /**
   * Reserve stock for a pending order.
   */
  @Operation
  com.example.inventory.ReservationOutput reserveStock(com.example.inventory.ReservationInput input);
}
