// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class ReserveStockOutput {
  private boolean reserved;

  /**
   * Whether the stock was successfully reserved.
   */
  @JsonProperty("reserved")
  public boolean getReserved() { return reserved; }
  @JsonProperty("reserved")
  public void setReserved(boolean value) { this.reserved = value; }
}
