# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional
from dataclasses import dataclass
from nexusrpc import Operation, service


@dataclass
class GetUserInput:
    userId: str
    """User ID for the user."""


@dataclass
class User:
    """A user."""

    email: Optional[str] = None
    """Email for the user."""

    userId: Optional[str] = None
    """User ID for the user."""


@dataclass
class GetUserOutput:
    user: User


@dataclass
class SetUserInput:
    user: User


@dataclass
class SetUserOutput:
    user: User


@dataclass
class DeleteUserInput:
    userId: str
    """User ID for the user."""


@service
class UserService:
    """A service for managing users."""

    get_user: Operation[GetUserInput, GetUserOutput] = Operation(name="getUser")
    """Get a user."""

    set_user: Operation[SetUserInput, SetUserOutput] = Operation(name="setUser")
    """Create or update a user."""

    delete_user: Operation[DeleteUserInput, None] = Operation(name="deleteUser")
    """Delete a user."""
