# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import ConfigDict, Field, BaseModel, model_validator
from typing import Optional, Any, get_origin
from nexusrpc import service, Operation


class _NexusBase(BaseModel):
    @model_validator(mode="before")
    @classmethod
    def _coerce_null_lists(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for name, field in cls.model_fields.items():
                if get_origin(field.annotation) is list:
                    key = field.alias or name
                    if key in data and data[key] is None:
                        data[key] = []
                    elif name in data and data[name] is None:
                        data[name] = []
        return data


class GetUserInput(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    user_id: str = Field(..., alias="userId")
    """User ID for the user."""


class User(_NexusBase):
    """A user."""

    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    email: Optional[str] = None
    """Email for the user."""

    user_id: Optional[str] = Field(None, alias="userId")
    """User ID for the user."""


class GetUserOutput(_NexusBase):
    user: User


class SetUserInput(_NexusBase):
    user: User


class SetUserOutput(_NexusBase):
    user: User


class DeleteUserInput(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    user_id: str = Field(..., alias="userId")
    """User ID for the user."""


@service
class UserService:
    """A service for managing users."""

    get_user: Operation[GetUserInput, GetUserOutput] = Operation(name="getUser")
    """Get a user."""

    set_user: Operation[SetUserInput, SetUserOutput] = Operation(name="setUser")
    """Create or update a user."""

    delete_user: Operation[DeleteUserInput, None] = Operation(name="deleteUser")
    """Delete a user."""
