# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional
from nexusrpc import service, Operation


class GetUserInput(BaseModel):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    user_id: str = Field(..., alias="userId")
    """User ID for the user."""


class User(BaseModel):
    """A user."""

    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    email: Optional[str] = None
    """Email for the user."""

    user_id: Optional[str] = Field(None, alias="userId")
    """User ID for the user."""


class GetUserOutput(BaseModel):
    user: User


class SetUserInput(BaseModel):
    user: User


class SetUserOutput(BaseModel):
    user: User


class DeleteUserInput(BaseModel):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    user_id: str = Field(..., alias="userId")
    """User ID for the user."""


@service
class UserService:
    """A service for managing users."""

    get_user: Operation[GetUserInput, GetUserOutput] = Operation(name="getUser")
    """Get a user."""

    set_user: Operation[SetUserInput, SetUserOutput] = Operation(name="setUser")
    """Create or update a user."""

    delete_user: Operation[DeleteUserInput, None] = Operation(name="deleteUser")
    """Delete a user."""
