// Code generated by nexus-rpc-gen. DO NOT EDIT.

package services

import "github.com/example/inventory/types"
import "github.com/nexus-rpc/sdk-go/nexus"

// An inventory tracking service that demonstrates using $langRef to reference types that
// already exist in your target language instead of generating new ones.
var InventoryService = struct {
	ServiceName                             string
	// Add a new item to the inventory.     
	AddItem                                 nexus.OperationReference[types.AddItemInput, types.AddItemOutput]
	// Get current stock levels for an item.
	GetItemStock                            nexus.OperationReference[types.StockQuery, types.StockLevel]
	// Reserve stock for a pending order.   
	ReserveStock                            nexus.OperationReference[types.ReservationRequest, types.ReservationResult]
}{
	ServiceName:  "InventoryService",
	AddItem:      nexus.NewOperationReference[types.AddItemInput, types.AddItemOutput]("addItem"),
	GetItemStock: nexus.NewOperationReference[types.StockQuery, types.StockLevel]("getItemStock"),
	ReserveStock: nexus.NewOperationReference[types.ReservationRequest, types.ReservationResult]("reserveStock"),
}
