// Generated by nexus-rpc-gen. DO NOT EDIT!

import * as nexus from "nexus-rpc";
import type { AddItemInput, AddItemOutput, ReservationRequest, ReservationResult, StockLevel, StockQuery } from "./types.js";

/**
 * An inventory tracking service that demonstrates using $langRef to reference types that
 * already exist in your target language instead of generating new ones.
 */
export const inventoryService = nexus.service("InventoryService", {
  /**
   * Add a new item to the inventory.
   */
  addItem: nexus.operation<AddItemInput, AddItemOutput>(),

  /**
   * Get current stock levels for an item.
   */
  getItemStock: nexus.operation<StockQuery, StockLevel>(),

  /**
   * Reserve stock for a pending order.
   */
  reserveStock: nexus.operation<ReservationRequest, ReservationResult>(),
});
