// Code generated by nexus-rpc-gen. DO NOT EDIT.

package main

import "github.com/example/inventory/types"
import "github.com/nexus-rpc/sdk-go/nexus"

// An inventory tracking service that demonstrates using $langRef to reference types that
// already exist in your target language instead of generating new ones.
var InventoryService = struct {
	ServiceName                             string
	// Add a new item to the inventory.     
	AddItem                                 nexus.OperationReference[AddItemInput, AddItemOutput]
	// Get current stock levels for an item.
	GetItemStock                            nexus.OperationReference[GetItemStockInput, types.StockLevel]
	// Reserve stock for a pending order.   
	ReserveStock                            nexus.OperationReference[types.ReservationRequest, ReserveStockOutput]
}{
	ServiceName:  "InventoryService",
	AddItem:      nexus.NewOperationReference[AddItemInput, AddItemOutput]("addItem"),
	GetItemStock: nexus.NewOperationReference[GetItemStockInput, types.StockLevel]("getItemStock"),
	ReserveStock: nexus.NewOperationReference[types.ReservationRequest, ReserveStockOutput]("reserveStock"),
}

type AddItemInput struct {
	// Starting quantity to stock.          
	InitialQuantity                  int64  `json:"initialQuantity"`
	// Human-readable item name.            
	Name                             string `json:"name"`
	// Stock-keeping unit identifier.       
	Sku                              string `json:"sku"`
}

type AddItemOutput struct {
	// Whether the item was successfully added.     
	Added                                      bool `json:"added"`
}

type GetItemStockInput struct {
	// The SKU to look up.       
	Sku                   string `json:"sku"`
}

type ReserveStockOutput struct {
	// Whether the stock was successfully reserved.     
	Reserved                                       bool `json:"reserved"`
}
