// <auto-generated />
#pragma warning disable CS8618

namespace NexusServices
{
    using NexusRpc;
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// A service for all types of operations
    /// </summary>
    [NexusService]
    public interface IKitchenSinkService
    {
        /// <summary>
        /// Counts the characters in the string
        /// </summary>
        [NexusOperation("scalarArgScalarResult")]
        long ScalarArgScalarResult(string input);

        /// <summary>
        /// Counts the characters in a string
        /// </summary>
        [NexusOperation("complexArgComplexResultInline")]
        KitchenSinkServiceComplexArgComplexResultInlineOutput ComplexArgComplexResultInline(KitchenSinkServiceComplexArgComplexResultInlineInput input);

        [NexusOperation("scalarArgScalarResultExternal")]
        long ScalarArgScalarResultExternal(string input);

        [NexusOperation("complexArgComplexResultExternal")]
        ComplexOutput ComplexArgComplexResultExternal(ComplexInput input);
    }

    [NexusService("Strange{Item}")]
    public interface IStrangeItem
    {
        [NexusOperation("Strange{Item}")]
        PurpleStrangeItem StrangeItem(StrangeItem input);

        [NexusOperation("StrangeItem")]
        void StrangeItem2();
    }

    [NexusService("StrangeItem")]
    public interface IStrangeItem2
    {
    }

    [NexusService]
    public interface IReservedWordService
    {
        [NexusOperation("ToString")]
        void ToStringOperation();
    }

    [NexusService]
    public interface IExistingTypesService
    {
        [NexusOperation("specificTypesForSomeLangs")]
        NexusServices.MyExistingType.MyExistingNestedType SpecificTypesForSomeLangs(ComplexInput input);

        [NexusOperation("specificTypesForOtherLangs")]
        ComplexOutput SpecificTypesForOtherLangs(NexusServices.MyExistingType input);
    }

    [NexusService]
    public interface IDateService
    {
        [NexusOperation("dateOperation")]
        void DateOperation(DateInput input);
    }

    /// <summary>
    /// Input type
    /// </summary>
    public partial class KitchenSinkServiceComplexArgComplexResultInlineInput
    {
        /// <summary>
        /// String to count
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("string")]
        public string String { get; set; }
    }

    /// <summary>
    /// Output type
    /// </summary>
    public partial class KitchenSinkServiceComplexArgComplexResultInlineOutput
    {
        /// <summary>
        /// Count of characters
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("characterCount")]
        public long? CharacterCount { get; set; }
    }

    public partial class ComplexInput
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("selfRef")]
        public ComplexInput SelfRef { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("someSharedObj")]
        public SharedObject SomeSharedObj { get; set; }
    }

    public partial class SharedObject
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("someField")]
        public long? SomeField { get; set; }
    }

    public partial class ComplexOutput
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("selfRef")]
        public ComplexOutput SelfRef { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("someSharedObj")]
        public SharedObject SomeSharedObj { get; set; }
    }

    public partial class StrangeItem
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("someField")]
        public long? SomeField { get; set; }
    }

    public partial class PurpleStrangeItem
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("someField")]
        public long? SomeField { get; set; }
    }

    public partial class DateInput
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("date")]
        public DateTimeOffset? Date { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("dateTime")]
        public DateTimeOffset? DateTime { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("time")]
        public DateTimeOffset? Time { get; set; }
    }
}
