import {
  ArrayType,
  ClassType,
  ConvenienceRenderer,
  MapType,
  Name,
  Namer,
  pythonOptions,
  PythonRenderer,
  PythonTargetLanguage,
  Type,
  UnionType,
  type LanguageName,
  type OptionValues,
  type RenderContext,
  type RendererOptions,
  type Sourcelike,
} from "quicktype-core";
import { RenderAdapter, type RenderAccessible } from "./render-adapter.js";
import type { PreparedService, PreparedTypeReference } from "./generator.js";
import { splitDescription } from "./utility.js";

// Change some defaults globally
pythonOptions.justTypes.definition.defaultValue = true;
pythonOptions.features.definition.defaultValue = "3.7";
pythonOptions.nicePropertyNames.definition.defaultValue = true;

export class PythonLanguageWithNexus extends PythonTargetLanguage {
  protected override makeRenderer<Lang extends LanguageName = "python">(
    renderContext: RenderContext,
    untypedOptionValues: RendererOptions<Lang>,
  ): PythonRenderer {
    const adapter = new PythonRenderAdapter(
      super.makeRenderer(renderContext, untypedOptionValues),
      untypedOptionValues,
    );
    adapter.assertValidOptions();
    return adapter.makeRenderer({
      emitSourceStructure(original, givenOutputFilename) {
        // Generated comment
        adapter.render.emitLine("# Generated by nexus-rpc-gen. DO NOT EDIT!");
        adapter.render.emitLine("# pyright: reportDeprecated=false");
        adapter.render.ensureBlankLine();

        // We need to add the future annotation
        // TODO(cretz): Have option to remove this?
        adapter.render.emitLine("from __future__ import annotations");
        adapter.render.ensureBlankLine();
        original(givenOutputFilename);
        // Emit services immediately after the model types so the public API
        // stays contiguous. Temporal Nexus payload helpers are emitted after.
        adapter.emitServices();
        adapter.emitTemporalNexusPayloadSupport();
        adapter.emitTemporalNexusPayloadRegistry();
        adapter.render.finishFile(adapter.makeFileName());
      },
      emitClass(_original, t) {
        adapter.emitClass(t);
      },
      emitImports(original) {
        original();
        adapter.emitAdditionalImports();
      },
    });
  }
}

type PythonRenderAccessible = PythonRenderer &
  RenderAccessible & {
    readonly pyOptions: OptionValues<typeof pythonOptions>;
    declareType<T extends Type>(t: T, emitter: () => void): void;
    emitBlock(line: Sourcelike, f: () => void): void;
    emitClass(t: ClassType): void;
    emitClosingCode(): void;
    emitImports(): void;
    emitSourceStructure(givenOutputFilename: string): void;
    pythonType(t: Type, isRootTypeDefinition: boolean): Sourcelike;
    string(s: string): Sourcelike;
    typeHint(...sl: Sourcelike[]): Sourcelike;
    withImport(module: string, name: string): Sourcelike;
  };

const emptyNameMap: ReadonlyMap<Name, string> = new Map();

type TemporalTerminalRewriteKind = "payload" | "payloads";

type TemporalFieldRewrite =
  | {
      kind: "payload";
      jsonName: string;
    }
  | {
      kind: "payloadMap";
      jsonName: string;
      messageType: string;
    }
  | {
      kind: "payloads";
      jsonName: string;
    }
  | {
      kind: "object";
      jsonName: string;
      helperName: string;
    }
  | {
      kind: "array";
      jsonName: string;
      helperName: string;
    }
  | {
      kind: "map";
      jsonName: string;
      helperName: string;
    };

interface TemporalClassRewritePlan {
  typeName: string;
  helperName: string;
  directRewriteKind?: TemporalTerminalRewriteKind;
  onlyWhenVisitSearchAttributes?: boolean;
  fieldRewrites: TemporalFieldRewrite[];
}

interface TemporalOperationPayloadRewriter {
  serviceName: string;
  operationName: string;
  inputTypeName: string;
  helperName: string;
}

class PythonRenderAdapter extends RenderAdapter<PythonRenderAccessible> {
  private readonly typeNamer: Namer;
  private readonly propertyNamer: Namer;
  private temporalClassRewritePlans:
    | Map<string, TemporalClassRewritePlan>
    | undefined;
  private temporalClassRewritePlanInProgress:
    | Set<string>
    | undefined;
  private nexusPayloadRewriters:
    | readonly TemporalOperationPayloadRewriter[]
    | undefined;

  constructor(render: ConvenienceRenderer, rendererOptions: RendererOptions) {
    super(render, rendererOptions);
    this.typeNamer = this.render.makeNamedTypeNamer();
    this.propertyNamer = this.render.namerForObjectProperty();
  }

  assertValidOptions() {
    // Currently, we only support specific Python options
    if (!this.render.pyOptions.justTypes) {
      throw new Error("Python option for just-types must be set");
    }
    if (!this.render.pyOptions.features.typeHints) {
      throw new Error("Python option to include type hints must be set");
    }
  }

  makeFileName() {
    // If there is a single service, use that, otherwise use the
    // filename sans extensions to build it
    const services = Object.entries(this.schema.services);
    const name =
      services.length == 1
        ? services[0][0]
        : this.nexusRendererOptions.firstFilenameSansExtensions;
    return this.propertyNamer.nameStyle(name) + ".py";
  }

  emitAdditionalImports() {
    if (
      [...this.render.topLevels.values()].some(
        (type) => type instanceof ClassType,
      )
    ) {
      this.render.emitLine("from dataclasses import dataclass");
    }
    if (Object.keys(this.schema.services).length > 0) {
      this.render.emitLine("from nexusrpc import Operation, service");
    }
    // We have to emit imports for existing types with dots. Unlike the existing
    // withImport/emitImports, we do not want from X import Y, we want just
    // import and we will fully-qualify the types at the usage site.
    const toImport: string[] = [];
    for (const svcSchema of Object.values(this.schema.services)) {
      for (const opSchema of Object.values(svcSchema.operations)) {
        for (const type of [opSchema.input, opSchema.output]) {
          if (type?.kind == "existing") {
            const lastDot = type.name.lastIndexOf(".");
            if (
              lastDot >= 0 &&
              !toImport.includes(type.name.slice(0, lastDot))
            ) {
              toImport.push(type.name.slice(0, lastDot));
            }
          }
        }
      }
    }
    toImport.sort();
    for (const module_ of toImport) {
      this.render.emitLine("import ", module_);
    }
    if (
      this.nexusRendererOptions.temporalNexusPayloadCodecSupport &&
      this.getNexusPayloadRewriters().length > 0
    ) {
      this.render.emitLine("import collections.abc");
      this.render.emitLine("import json");
      this.render.emitLine(
        "from google.protobuf.json_format import MessageToDict, ParseDict",
      );
      this.render.emitLine("import temporalio.api.common.v1");
    }
  }

  emitTemporalNexusPayloadSupport() {
    if (
      !this.nexusRendererOptions.temporalNexusPayloadCodecSupport ||
      this.getNexusPayloadRewriters().length == 0
    ) {
      return;
    }

    this.render.ensureBlankLine();
    this.render.emitBlock("class _TemporalNexusPayloadRewriter:", () => {
      this.render.emitBlock(
        [
          "def __init__(",
          "self, ",
          "payload_visitor: collections.abc.Callable[[collections.abc.Sequence[temporalio.api.common.v1.Payload]], collections.abc.Awaitable[list[temporalio.api.common.v1.Payload]]], ",
          "visit_search_attributes: bool = False",
          "):",
        ],
        () => {
          this.render.emitLine("self._payload_visitor = payload_visitor");
          this.render.emitLine(
            "self._visit_search_attributes = visit_search_attributes",
          );
        },
      );
      this.render.ensureBlankLine();
      this.render.emitBlock(
        ["async def _rewrite_payload_json(", "self, value: dict", ") -> dict:"],
        () => {
          this.render.emitLine(
            "payload = ParseDict(value, ",
            "temporalio.api.common.v1.Payload()",
            ")",
          );
          this.render.emitLine(
            "[rewritten_payload] = await self._payload_visitor([payload])",
          );
          this.render.emitLine("return MessageToDict(rewritten_payload)");
        },
      );
      this.render.ensureBlankLine();
      this.render.emitBlock(
        [
          "async def _rewrite_payloads_json(",
          "self, value: dict",
          ") -> dict:",
        ],
        () => {
          this.render.emitLine(
            "payloads = ParseDict(value, ",
            "temporalio.api.common.v1.Payloads()",
            ")",
          );
          this.render.emitLine(
            "rewritten_payloads = await self._payload_visitor(payloads.payloads)",
          );
          this.render.emitLine("del payloads.payloads[:]");
          this.render.emitLine("payloads.payloads.extend(rewritten_payloads)");
          this.render.emitLine("return MessageToDict(payloads)");
        },
      );
      this.render.ensureBlankLine();
      this.render.emitBlock(
        [
          "async def _rewrite_payload_map_json(",
          "self, message_type: type, value: dict",
          ") -> dict:",
        ],
        () => {
          this.render.emitLine("message = message_type()");
          this.render.emitLine("keys = list(value.keys())");
          this.render.emitLine(
            "rewritten_payloads = await self._payload_visitor([ParseDict(value[key], temporalio.api.common.v1.Payload()) for key in keys])",
          );
          this.render.emitBlock(
            "for key, rewritten_payload in zip(keys, rewritten_payloads):",
            () => {
              this.render.emitLine(
                "message.fields[key].CopyFrom(rewritten_payload)",
              );
            },
          );
          this.render.emitLine(
            'return MessageToDict(message).get("fields", {})',
          );
        },
      );
      for (const plan of this.getTemporalClassRewritePlans().values()) {
        this.render.ensureBlankLine();
        this.emitTemporalClassRewritePlan(plan);
      }
    });
  }

  emitTemporalNexusPayloadRegistry() {
    const payloadRewriters = this.getNexusPayloadRewriters();
    if (
      !this.nexusRendererOptions.temporalNexusPayloadCodecSupport ||
      payloadRewriters.length == 0
    ) {
      return;
    }

    this.render.ensureBlankLine(2);
    for (const rewriter of payloadRewriters) {
      this.render.emitBlock(
        [
          "async def ",
          rewriter.helperName,
          "(",
          "payload: temporalio.api.common.v1.Payload, ",
          "payload_visitor: collections.abc.Callable[[collections.abc.Sequence[temporalio.api.common.v1.Payload]], collections.abc.Awaitable[list[temporalio.api.common.v1.Payload]]]",
          ", visit_search_attributes: bool = False",
          ") -> temporalio.api.common.v1.Payload:",
        ],
        () => {
          this.render.emitLine("try:");
          this.render.indent(() => {
            this.render.emitLine("value = json.loads(payload.data)");
          });
          this.render.emitLine("except json.JSONDecodeError:");
          this.render.indent(() => {
            this.render.emitLine("return payload");
          });
          this.render.emitLine("if not isinstance(value, dict):");
          this.render.indent(() => {
            this.render.emitLine("return payload");
          });
          this.render.emitLine(
            "rewriter = _TemporalNexusPayloadRewriter(",
            "payload_visitor, visit_search_attributes)",
          );
          this.render.emitLine(
            "rewritten = await ",
            "rewriter.",
            this.makeTemporalClassRewriteHelperName(rewriter.inputTypeName),
            "(value)",
          );
          this.render.emitLine(
            'return temporalio.api.common.v1.Payload(metadata=dict(payload.metadata), data=json.dumps(rewritten, separators=(",", ":"), sort_keys=True).encode())',
          );
        },
      );
      this.render.ensureBlankLine();
    }

    this.render.emitLine("__temporal_nexus_payload_rewriters__ = {");
    this.render.indent(() => {
      for (const rewriter of payloadRewriters) {
        this.render.emitLine(
          "(",
          this.render.string(rewriter.serviceName),
          ", ",
          this.render.string(rewriter.operationName),
          "): ",
          rewriter.helperName,
          ",",
        );
      }
    });
    this.render.emitLine("}");
    this.render.ensureBlankLine();
  }

  getNexusPayloadRewriters(): readonly TemporalOperationPayloadRewriter[] {
    if (this.nexusPayloadRewriters) {
      return this.nexusPayloadRewriters;
    }
    this.nexusPayloadRewriters = Object.entries(this.schema.services).flatMap(
      ([serviceName, service]) =>
        Object.entries(service.operations).flatMap(
          ([operationName, operation]) => {
            if (operation.input?.kind != "jsonSchema") {
              return [];
            }
            const plan = this.getTemporalClassRewritePlanByName(
              operation.input.name,
            );
            if (!plan) {
              return [];
            }
            return [
              {
                serviceName,
                operationName,
                inputTypeName: operation.input.name,
                helperName: this.makeTemporalNexusRewriterFunctionName(
                  operation.input.name,
                ),
              },
            ];
          },
        ),
    );
    return this.nexusPayloadRewriters;
  }

  getTemporalClassRewritePlans(): ReadonlyMap<
    string,
    TemporalClassRewritePlan
  > {
    if (!this.temporalClassRewritePlans) {
      this.temporalClassRewritePlans = new Map();
      for (const rewriter of this.getNexusPayloadRewriters()) {
        this.getTemporalClassRewritePlanByName(rewriter.inputTypeName);
      }
    }
    return this.temporalClassRewritePlans;
  }

  getTemporalClassRewritePlanByName(
    typeName: string,
  ): TemporalClassRewritePlan | undefined {
    const topLevel = this.render.topLevels.get(typeName);
    if (!(topLevel instanceof ClassType)) {
      return undefined;
    }
    return this.getTemporalClassRewritePlan(topLevel);
  }

  getTemporalClassRewritePlan(
    type: ClassType,
  ): TemporalClassRewritePlan | undefined {
    const typeName = this.getNamedTypeName(type);
    const existingPlan = this.temporalClassRewritePlans?.get(typeName);
    if (existingPlan) {
      return existingPlan;
    }
    if (this.temporalClassRewritePlanInProgress?.has(typeName)) {
      return undefined;
    }
    if (!this.temporalClassRewritePlanInProgress) {
      this.temporalClassRewritePlanInProgress = new Set();
    }
    this.temporalClassRewritePlanInProgress.add(typeName);

    try {
      const directRewriteKind = this.getTemporalDirectRewriteKind(typeName);
      const fieldRewrites: TemporalFieldRewrite[] = [];
      for (const [jsonName, property] of type.getProperties()) {
        const terminalRewrite = this.getTemporalTerminalFieldRewrite(
          typeName,
          jsonName,
        );
        if (terminalRewrite) {
          fieldRewrites.push(terminalRewrite);
          continue;
        }
        const childRewrite = this.getTemporalChildFieldRewrite(
          property.type,
          jsonName,
        );
        if (childRewrite) {
          fieldRewrites.push(childRewrite);
        }
      }

      if (!directRewriteKind && fieldRewrites.length == 0) {
        return undefined;
      }

      const plan: TemporalClassRewritePlan = {
        typeName,
        helperName: this.makeTemporalClassRewriteHelperName(typeName),
        directRewriteKind,
        onlyWhenVisitSearchAttributes: typeName == "SearchAttributes",
        fieldRewrites,
      };
      if (!this.temporalClassRewritePlans) {
        this.temporalClassRewritePlans = new Map();
      }
      this.temporalClassRewritePlans.set(typeName, plan);
      return plan;
    } finally {
      this.temporalClassRewritePlanInProgress.delete(typeName);
    }
  }

  getTemporalDirectRewriteKind(
    typeName: string,
  ): TemporalTerminalRewriteKind | undefined {
    if (typeName == "Payload") {
      return "payload";
    }
    if (typeName == "Payloads" || typeName == "Input") {
      return "payloads";
    }
    return undefined;
  }

  getTemporalTerminalFieldRewrite(
    typeName: string,
    jsonName: string,
  ): TemporalFieldRewrite | undefined {
    if (typeName == "Header" && jsonName == "fields") {
      return {
        kind: "payloadMap",
        jsonName,
        messageType: "temporalio.api.common.v1.Header",
      };
    }
    if (typeName == "Memo" && jsonName == "fields") {
      return {
        kind: "payloadMap",
        jsonName,
        messageType: "temporalio.api.common.v1.Memo",
      };
    }
    if (typeName == "SearchAttributes" && jsonName == "indexedFields") {
      return {
        kind: "payloadMap",
        jsonName,
        messageType: "temporalio.api.common.v1.SearchAttributes",
      };
    }
    if (
      typeName == "UserMetadata" &&
      ["summary", "details"].includes(jsonName)
    ) {
      return { kind: "payload", jsonName };
    }
    if (typeName == "Input" && jsonName == "payloads") {
      return { kind: "payloads", jsonName };
    }
    return undefined;
  }

  getTemporalChildFieldRewrite(
    type: Type,
    jsonName: string,
  ): TemporalFieldRewrite | undefined {
    const normalizedType = this.unwrapNullableType(type);
    if (!normalizedType) {
      return undefined;
    }
    if (normalizedType instanceof ClassType) {
      const plan = this.getTemporalClassRewritePlan(normalizedType);
      return plan
        ? { kind: "object", jsonName, helperName: plan.helperName }
        : undefined;
    }
    if (normalizedType instanceof ArrayType) {
      const itemType = this.unwrapNullableType(normalizedType.items);
      if (itemType instanceof ClassType) {
        const plan = this.getTemporalClassRewritePlan(itemType);
        return plan
          ? { kind: "array", jsonName, helperName: plan.helperName }
          : undefined;
      }
      return undefined;
    }
    if (normalizedType instanceof MapType) {
      const valueType = this.unwrapNullableType(normalizedType.values);
      if (valueType instanceof ClassType) {
        const plan = this.getTemporalClassRewritePlan(valueType);
        return plan
          ? { kind: "map", jsonName, helperName: plan.helperName }
          : undefined;
      }
    }
    return undefined;
  }

  unwrapNullableType(type: Type): Type | undefined {
    if (!(type instanceof UnionType)) {
      return type;
    }
    const nonNullMembers = [...type.members].filter(
      (member) => member.kind != "null",
    );
    return nonNullMembers.length == 1 ? nonNullMembers[0] : undefined;
  }

  getNamedTypeName(type: Type): string {
    return (
      this.render.names.get(this.render.nameForNamedType(type)) ??
      type.getCombinedName()
    );
  }

  emitTemporalClassRewritePlan(plan: TemporalClassRewritePlan) {
    this.render.emitBlock(
      ["async def ", plan.helperName, "(", "self, value: dict", ") -> dict:"],
      () => {
        if (plan.onlyWhenVisitSearchAttributes) {
          this.render.emitLine("if not self._visit_search_attributes:");
          this.render.indent(() => {
            this.render.emitLine("return value");
          });
        }
        if (plan.directRewriteKind == "payload") {
          this.render.emitLine(
            "return await self._rewrite_payload_json(value)",
          );
          return;
        }
        if (plan.directRewriteKind == "payloads") {
          this.render.emitLine(
            "return await self._rewrite_payloads_json(value)",
          );
          return;
        }
        this.render.emitLine("rewritten = dict(value)");
        for (const fieldRewrite of plan.fieldRewrites) {
          this.emitTemporalFieldRewrite(fieldRewrite);
        }
        this.render.emitLine("return rewritten");
      },
    );
  }

  emitTemporalFieldRewrite(fieldRewrite: TemporalFieldRewrite) {
    const fieldReference = `rewritten[${JSON.stringify(fieldRewrite.jsonName)}]`;
    const fieldLookup = `rewritten.get(${JSON.stringify(fieldRewrite.jsonName)})`;
    if (fieldRewrite.kind == "payload") {
      this.render.emitLine("if ", fieldLookup, " is not None:");
      this.render.indent(() => {
        this.render.emitLine(
          fieldReference,
          " = await self._rewrite_payload_json(",
          fieldReference,
          ")",
        );
      });
      return;
    }
    if (fieldRewrite.kind == "payloads") {
      this.render.emitLine("if ", fieldLookup, " is not None:");
      this.render.indent(() => {
        this.render.emitLine(
          fieldReference,
          " = await self._rewrite_payloads_json(",
          fieldReference,
          ")",
        );
      });
      return;
    }
    if (fieldRewrite.kind == "payloadMap") {
      this.render.emitLine("if ", fieldLookup, " is not None:");
      this.render.indent(() => {
        this.render.emitLine(
          fieldReference,
          " = await self._rewrite_payload_map_json(",
          fieldRewrite.messageType,
          ", ",
          fieldReference,
          ")",
        );
      });
      return;
    }
    if (fieldRewrite.kind == "object") {
      this.render.emitLine("if ", fieldLookup, " is not None:");
      this.render.indent(() => {
        this.render.emitLine(
          fieldReference,
          " = await ",
          "self.",
          fieldRewrite.helperName,
          "(",
          fieldReference,
          ")",
        );
      });
      return;
    }
    if (fieldRewrite.kind == "array") {
      this.render.emitLine("if ", fieldLookup, " is not None:");
      this.render.indent(() => {
        this.render.emitLine(
          fieldReference,
          " = [await ",
          "self.",
          fieldRewrite.helperName,
          "(item) for item in ",
          fieldReference,
          "]",
        );
      });
      return;
    }
    this.render.emitLine("if ", fieldLookup, " is not None:");
    this.render.indent(() => {
      this.render.emitLine(fieldReference, " = {");
      this.render.indent(() => {
        this.render.emitLine(
          "key: await ",
          "self.",
          fieldRewrite.helperName,
          "(item)",
        );
        this.render.emitLine("for key, item in ", fieldReference, ".items()");
      });
      this.render.emitLine("}");
    });
  }

  emitServices() {
    for (const [serviceName, serviceSchema] of Object.entries(
      this.schema.services,
    )) {
      this.emitService(serviceName, serviceSchema);
    }
  }

  emitService(serviceName: string, serviceSchema: PreparedService) {
    this.render.ensureBlankLine(2);
    const typeName = this.makeServiceTypeName(
      this.typeNamer.nameStyle(serviceName),
    );
    // Decorator
    this.render.emitLine(
      "@",
      this.render.withImport("nexusrpc", "service"),
      serviceName == typeName
        ? []
        : ["(name=", this.render.string(serviceName), ")"],
    );
    // Service class with each property
    this.render.emitBlock(["class ", typeName, ":"], () => {
      this.render.emitDescription(splitDescription(serviceSchema.description));
      if (Object.entries(serviceSchema.operations).length == 0) {
        this.render.emitLine("pass");
      }
      const propertyNamesInUse = {};
      this.render.forEachWithBlankLines(
        Object.entries(serviceSchema.operations),
        "interposing",
        (op, opName, pos) => {
          const propertyName = this.makeOperationFunctionName(
            this.propertyNamer.nameStyle(opName),
            propertyNamesInUse,
          );
          this.render.emitLine(
            propertyName,
            ": ",
            this.render.withImport("nexusrpc", "Operation"),
            "[",
            this.getNexusType(op.input) ?? "None",
            ", ",
            this.getNexusType(op.output) ?? "None",
            "]",
            opName == propertyName
              ? []
              : [
                  " = ",
                  this.render.withImport("nexusrpc", "Operation"),
                  "(name=",
                  this.render.string(opName),
                  ")",
                ],
          );
          this.render.emitDescription(splitDescription(op.description));
        },
      );
    });
  }

  emitClass(t: ClassType) {
    const properties: {
      jsonName: string;
      type: Type;
    }[] = [];
    this.render.forEachClassProperty(t, "none", (_name, jsonName, cp) => {
      properties.push({ jsonName, type: cp.type });
    });
    properties.sort((a, b) => {
      const aOptional = this.isOptionalType(a.type);
      const bOptional = this.isOptionalType(b.type);
      return Number(aOptional) - Number(bOptional);
    });
    this.render.emitLine(
      "@",
      this.render.withImport("dataclasses", "dataclass"),
    );
    this.render.declareType(t, () => {
      if (t.getProperties().size === 0) {
        this.render.emitLine("pass");
        return;
      }
      for (const { jsonName, type } of properties) {
        const typeSource = this.render.pythonType(type, true);
        this.render.emitLine(jsonName, ": ", typeSource);
        this.render.emitDescription(
          this.render.descriptionForClassProperty(t, jsonName),
        );
      }
      this.render.ensureBlankLine();
    });
  }

  isOptionalType(type: Type): boolean {
    return (
      type instanceof UnionType &&
      [...type.members].some((member) => member.kind == "null")
    );
  }

  makeTemporalNexusRewriterFunctionName(inputTypeName: string): string {
    return `_temporal_nexus_rewrite_${this.propertyNamer.nameStyle(inputTypeName)}`;
  }

  makeTemporalClassRewriteHelperName(typeName: string): string {
    return `_temporal_nexus_rewrite_${this.propertyNamer.nameStyle(typeName)}_json`;
  }

  getNexusType(
    reference: PreparedTypeReference | undefined,
  ): Sourcelike | undefined {
    if (!reference) {
      return undefined;
    } else if (reference.kind == "existing") {
      return reference.name;
    } else {
      const type = this.render.topLevels.get(reference.name);
      if (!type) {
        throw new Error(`Unable to find type for ${reference.name}`);
      }
      return this.render.pythonType(type, false);
    }
  }
}
