// <auto-generated />
#pragma warning disable CS8618, CS8601, CS8602
#nullable enable

namespace NexusServices
{
    using NexusRpc;
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// Exercises a broad set of JSON Schema features.
    /// </summary>
    [NexusService]
    public interface IJsonSchemaFeaturesService
    {
        [NexusOperation("roundTrip")]
        JsonSchemaFeaturesPayload RoundTrip(JsonSchemaFeaturesPayload input);
    }

    /// <summary>
    /// A payload intended to exercise many JSON Schema features.
    /// </summary>
    public partial class JsonSchemaFeaturesPayload
    {
        [JsonPropertyName("active")]
        public bool Active { get; set; }

        [JsonPropertyName("address")]
        public ShippingAddress Address { get; set; }

        [JsonPropertyName("contact")]
        public PrimaryContact Contact { get; set; }

        [JsonPropertyName("count")]
        public long Count { get; set; }

        [JsonPropertyName("fixedKind")]
        public FixedKind FixedKind { get; set; }

        [JsonPropertyName("history")]
        public HistoryEvent[] History { get; set; }

        [JsonPropertyName("id")]
        [JsonConverter(typeof(FluffyMinMaxLengthCheckConverter))]
        public string Id { get; set; }

        [JsonPropertyName("manager")]
        public Manager Manager { get; set; }

        [JsonPropertyName("metadata")]
        public Dictionary<string, string> Metadata { get; set; }

        [JsonPropertyName("nullableNote")]
        public string NullableNote { get; set; }

        [JsonPropertyName("pet")]
        public Cat Pet { get; set; }

        [JsonPropertyName("price")]
        [JsonConverter(typeof(MinMaxValueCheckConverter))]
        public double Price { get; set; }

        [JsonPropertyName("scoreMatrix")]
        public double[][] ScoreMatrix { get; set; }

        [JsonPropertyName("status")]
        public Status Status { get; set; }

        [JsonPropertyName("tags")]
        public string[] Tags { get; set; }

        [JsonPropertyName("timestamp")]
        public DateTimeOffset Timestamp { get; set; }

        [JsonPropertyName("variant")]
        public Actor Variant { get; set; }
    }

    public partial class ShippingAddress
    {
        [JsonPropertyName("city")]
        public string City { get; set; }

        [JsonPropertyName("countryCode")]
        [JsonConverter(typeof(PurpleMinMaxLengthCheckConverter))]
        public string CountryCode { get; set; }

        [JsonPropertyName("line1")]
        public string Line1 { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("postalCode")]
        public string PostalCode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("instructions")]
        public string Instructions { get; set; }

        [JsonPropertyName("residential")]
        public bool Residential { get; set; }
    }

    public partial class PrimaryContact
    {
        [JsonPropertyName("email")]
        public string Email { get; set; }

        [JsonPropertyName("method")]
        public Method Method { get; set; }
    }

    public partial class HistoryEvent
    {
        [JsonPropertyName("action")]
        public Action Action { get; set; }

        [JsonPropertyName("actor")]
        public Actor Actor { get; set; }

        [JsonPropertyName("at")]
        public DateTimeOffset At { get; set; }
    }

    public partial class Manager
    {
        [JsonPropertyName("email")]
        public string Email { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("department")]
        public string Department { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("reports")]
        public long? Reports { get; set; }
    }

    public partial class Cat
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("hunts")]
        public bool? Hunts { get; set; }

        [JsonPropertyName("kind")]
        public Kind Kind { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("breed")]
        public Breed? Breed { get; set; }
    }

    public enum Method { Email };

    public enum FixedKind { Payload };

    public enum Action { Created, Updated };

    public enum Breed { Herding, Hound, Working };

    public enum Kind { Cat, Dog };

    public enum Status { Active, Disabled, Pending };

    public partial struct Actor
    {
        public long? Integer;
        public string String;

        public static implicit operator Actor(long Integer) => new Actor { Integer = Integer };
        public static implicit operator Actor(string String) => new Actor { String = String };
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                MethodConverter.Singleton,
                FixedKindConverter.Singleton,
                ActionConverter.Singleton,
                ActorConverter.Singleton,
                BreedConverter.Singleton,
                KindConverter.Singleton,
                StatusConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class PurpleMinMaxLengthCheckConverter : JsonConverter<string>
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value.Length >= 2 && value.Length <= 2)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type string");
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            if (value.Length >= 2 && value.Length <= 2)
            {
                JsonSerializer.Serialize(writer, value, options);
                return;
            }
            throw new Exception("Cannot marshal type string");
        }

        public static readonly PurpleMinMaxLengthCheckConverter Singleton = new PurpleMinMaxLengthCheckConverter();
    }

    internal class MethodConverter : JsonConverter<Method>
    {
        public override bool CanConvert(Type t) => t == typeof(Method);

        public override Method Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "email")
            {
                return Method.Email;
            }
            throw new Exception("Cannot unmarshal type Method");
        }

        public override void Write(Utf8JsonWriter writer, Method value, JsonSerializerOptions options)
        {
            if (value == Method.Email)
            {
                JsonSerializer.Serialize(writer, "email", options);
                return;
            }
            throw new Exception("Cannot marshal type Method");
        }

        public static readonly MethodConverter Singleton = new MethodConverter();
    }

    internal class FixedKindConverter : JsonConverter<FixedKind>
    {
        public override bool CanConvert(Type t) => t == typeof(FixedKind);

        public override FixedKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value == "payload")
            {
                return FixedKind.Payload;
            }
            throw new Exception("Cannot unmarshal type FixedKind");
        }

        public override void Write(Utf8JsonWriter writer, FixedKind value, JsonSerializerOptions options)
        {
            if (value == FixedKind.Payload)
            {
                JsonSerializer.Serialize(writer, "payload", options);
                return;
            }
            throw new Exception("Cannot marshal type FixedKind");
        }

        public static readonly FixedKindConverter Singleton = new FixedKindConverter();
    }

    internal class ActionConverter : JsonConverter<Action>
    {
        public override bool CanConvert(Type t) => t == typeof(Action);

        public override Action Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "created":
                    return Action.Created;
                case "updated":
                    return Action.Updated;
            }
            throw new Exception("Cannot unmarshal type Action");
        }

        public override void Write(Utf8JsonWriter writer, Action value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Action.Created:
                    JsonSerializer.Serialize(writer, "created", options);
                    return;
                case Action.Updated:
                    JsonSerializer.Serialize(writer, "updated", options);
                    return;
            }
            throw new Exception("Cannot marshal type Action");
        }

        public static readonly ActionConverter Singleton = new ActionConverter();
    }

    internal class ActorConverter : JsonConverter<Actor>
    {
        public override bool CanConvert(Type t) => t == typeof(Actor);

        public override Actor Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            switch (reader.TokenType)
            {
                case JsonTokenType.Number:
                    var integerValue = reader.GetInt64();
                    return new Actor { Integer = integerValue };
                case JsonTokenType.String:
                    var stringValue = reader.GetString();
                    return new Actor { String = stringValue };
            }
            throw new Exception("Cannot unmarshal type Actor");
        }

        public override void Write(Utf8JsonWriter writer, Actor value, JsonSerializerOptions options)
        {
            if (value.Integer != null)
            {
                JsonSerializer.Serialize(writer, value.Integer.Value, options);
                return;
            }
            if (value.String != null)
            {
                JsonSerializer.Serialize(writer, value.String, options);
                return;
            }
            throw new Exception("Cannot marshal type Actor");
        }

        public static readonly ActorConverter Singleton = new ActorConverter();
    }

    internal class FluffyMinMaxLengthCheckConverter : JsonConverter<string>
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            if (value.Length >= 3 && value.Length <= 12)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type string");
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            if (value.Length >= 3 && value.Length <= 12)
            {
                JsonSerializer.Serialize(writer, value, options);
                return;
            }
            throw new Exception("Cannot marshal type string");
        }

        public static readonly FluffyMinMaxLengthCheckConverter Singleton = new FluffyMinMaxLengthCheckConverter();
    }

    internal class BreedConverter : JsonConverter<Breed>
    {
        public override bool CanConvert(Type t) => t == typeof(Breed);

        public override Breed Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "herding":
                    return Breed.Herding;
                case "hound":
                    return Breed.Hound;
                case "working":
                    return Breed.Working;
            }
            throw new Exception("Cannot unmarshal type Breed");
        }

        public override void Write(Utf8JsonWriter writer, Breed value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Breed.Herding:
                    JsonSerializer.Serialize(writer, "herding", options);
                    return;
                case Breed.Hound:
                    JsonSerializer.Serialize(writer, "hound", options);
                    return;
                case Breed.Working:
                    JsonSerializer.Serialize(writer, "working", options);
                    return;
            }
            throw new Exception("Cannot marshal type Breed");
        }

        public static readonly BreedConverter Singleton = new BreedConverter();
    }

    internal class KindConverter : JsonConverter<Kind>
    {
        public override bool CanConvert(Type t) => t == typeof(Kind);

        public override Kind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "cat":
                    return Kind.Cat;
                case "dog":
                    return Kind.Dog;
            }
            throw new Exception("Cannot unmarshal type Kind");
        }

        public override void Write(Utf8JsonWriter writer, Kind value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Kind.Cat:
                    JsonSerializer.Serialize(writer, "cat", options);
                    return;
                case Kind.Dog:
                    JsonSerializer.Serialize(writer, "dog", options);
                    return;
            }
            throw new Exception("Cannot marshal type Kind");
        }

        public static readonly KindConverter Singleton = new KindConverter();
    }

    internal class MinMaxValueCheckConverter : JsonConverter<double>
    {
        public override bool CanConvert(Type t) => t == typeof(double);

        public override double Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetDouble();
            if (value >= 0)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type double");
        }

        public override void Write(Utf8JsonWriter writer, double value, JsonSerializerOptions options)
        {
            if (value >= 0)
            {
                JsonSerializer.Serialize(writer, value, options);
                return;
            }
            throw new Exception("Cannot marshal type double");
        }

        public static readonly MinMaxValueCheckConverter Singleton = new MinMaxValueCheckConverter();
    }

    internal class StatusConverter : JsonConverter<Status>
    {
        public override bool CanConvert(Type t) => t == typeof(Status);

        public override Status Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "active":
                    return Status.Active;
                case "disabled":
                    return Status.Disabled;
                case "pending":
                    return Status.Pending;
            }
            throw new Exception("Cannot unmarshal type Status");
        }

        public override void Write(Utf8JsonWriter writer, Status value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Status.Active:
                    JsonSerializer.Serialize(writer, "active", options);
                    return;
                case Status.Disabled:
                    JsonSerializer.Serialize(writer, "disabled", options);
                    return;
                case Status.Pending:
                    JsonSerializer.Serialize(writer, "pending", options);
                    return;
            }
            throw new Exception("Cannot marshal type Status");
        }

        public static readonly StatusConverter Singleton = new StatusConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
