// Generated by nexus-rpc-gen. DO NOT EDIT!

package com.example.nexusservices;

import com.fasterxml.jackson.annotation.*;

public class GetUserInput {
  private String userID;

  /**
   * User ID for the user.
   */
  @JsonProperty("userId")
  public String getUserID() { return userID; }
  @JsonProperty("userId")
  public void setUserID(String value) { this.userID = value; }
}
