# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional, Union, List, Dict
from enum import Enum
from datetime import datetime
from nexusrpc import service, Operation


class ShippingAddress(BaseModel):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    city: str
    country_code: str = Field(..., alias="countryCode")
    line1: str
    residential: bool
    postal_code: Optional[str] = Field(None, alias="postalCode")
    instructions: Optional[str] = None


class Method(Enum):
    EMAIL = "email"


class PrimaryContact(BaseModel):
    email: str
    method: Method


class FixedKind(Enum):
    PAYLOAD = "payload"


class Action(Enum):
    CREATED = "created"
    UPDATED = "updated"


class HistoryEvent(BaseModel):
    action: Action
    actor: Union[int, str]
    at: datetime


class Manager(BaseModel):
    email: str
    name: str
    department: str
    reports: Optional[int] = None


class Breed(Enum):
    HERDING = "herding"
    HOUND = "hound"
    WORKING = "working"


class Kind(Enum):
    CAT = "cat"
    DOG = "dog"


class Cat(BaseModel):
    kind: Kind
    hunts: Optional[bool] = None
    breed: Optional[Breed] = None


class Status(Enum):
    ACTIVE = "active"
    DISABLED = "disabled"
    PENDING = "pending"


class JSONSchemaFeaturesPayload(BaseModel):
    """A payload intended to exercise many JSON Schema features."""

    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    active: bool
    address: ShippingAddress
    contact: PrimaryContact
    count: int
    fixed_kind: FixedKind = Field(..., alias="fixedKind")
    history: List[HistoryEvent]
    id: str
    manager: Manager
    metadata: Dict[str, str]
    pet: Cat
    price: float
    score_matrix: List[List[float]] = Field(..., alias="scoreMatrix")
    status: Status
    tags: List[str]
    timestamp: datetime
    variant: Union[int, str]
    nullable_note: Optional[str] = Field(None, alias="nullableNote")


@service(name="JsonSchemaFeaturesService")
class JSONSchemaFeaturesService:
    """Exercises a broad set of JSON Schema features."""

    round_trip: Operation[JSONSchemaFeaturesPayload, JSONSchemaFeaturesPayload] = Operation(name="roundTrip")
