# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from typing import Optional, Any, get_origin
from pydantic import ConfigDict, Field, BaseModel, model_validator
from datetime import datetime
from nexusrpc import service, Operation
import collections
import services.types


class _NexusBase(BaseModel):
    @model_validator(mode="before")
    @classmethod
    def _coerce_null_lists(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for name, field in cls.model_fields.items():
                if get_origin(field.annotation) is list:
                    key = field.alias or name
                    if key in data and data[key] is None:
                        data[key] = []
                    elif name in data and data[name] is None:
                        data[name] = []
        return data


class KitchenSinkServiceComplexArgComplexResultInlineInput(_NexusBase):
    """Input type"""

    string: Optional[str] = None
    """String to count"""


class KitchenSinkServiceComplexArgComplexResultInlineOutput(_NexusBase):
    """Output type"""

    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    character_count: Optional[int] = Field(None, alias="characterCount")
    """Count of characters"""


class SharedObject(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    some_field: Optional[int] = Field(None, alias="someField")


class ComplexInput(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    self_ref: Optional["ComplexInput"] = Field(None, alias="selfRef")
    some_shared_obj: Optional[SharedObject] = Field(None, alias="someSharedObj")


class ComplexOutput(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    self_ref: Optional["ComplexOutput"] = Field(None, alias="selfRef")
    some_shared_obj: Optional[SharedObject] = Field(None, alias="someSharedObj")


class StrangeItem(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    some_field: Optional[int] = Field(None, alias="someField")


class PurpleStrangeItem(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    some_field: Optional[int] = Field(None, alias="someField")


class DateInput(_NexusBase):
    model_config = ConfigDict(validate_by_name=True, validate_by_alias=True)

    date: Optional[datetime] = None
    date_time: Optional[datetime] = Field(None, alias="dateTime")
    time: Optional[datetime] = None


@service
class KitchenSinkService:
    """A service for all types of operations"""

    scalar_arg_scalar_result: Operation[str, int] = Operation(
        name="scalarArgScalarResult"
    )
    """Counts the characters in the string"""

    complex_arg_complex_result_inline: Operation[
        KitchenSinkServiceComplexArgComplexResultInlineInput,
        KitchenSinkServiceComplexArgComplexResultInlineOutput,
    ] = Operation(name="complexArgComplexResultInline")
    """Counts the characters in a string"""

    scalar_arg_scalar_result_external: Operation[str, int] = Operation(
        name="scalarArgScalarResultExternal"
    )

    complex_arg_complex_result_external: Operation[ComplexInput, ComplexOutput] = (
        Operation(name="complexArgComplexResultExternal")
    )


@service(name="Strange{Item}")
class StrangeItemService:
    strange_item: Operation[StrangeItem, PurpleStrangeItem] = Operation(
        name="Strange{Item}"
    )

    strange_item2: Operation[None, None] = Operation(name="StrangeItem")


@service(name="StrangeItem")
class StrangeItemService2:
    pass


@service
class ReservedWordService:
    to_string: Operation[None, None] = Operation(name="ToString")


@service
class ExistingTypesService:
    specific_types_for_some_langs: Operation[
        services.types.MyExistingType, ComplexOutput
    ] = Operation(name="specificTypesForSomeLangs")

    specific_types_for_other_langs: Operation[ComplexInput, collections.deque] = (
        Operation(name="specificTypesForOtherLangs")
    )


@service
class DateService:
    date_operation: Operation[DateInput, None] = Operation(name="dateOperation")
