# Generated by nexus-rpc-gen. DO NOT EDIT!
# pyright: reportDeprecated=false

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional
from datetime import datetime
from dataclasses import dataclass
from nexusrpc import Operation, service
import collections
import services.types


@dataclass
class KitchenSinkServiceComplexArgComplexResultInlineInput:
    """Input type"""

    string: Optional[str] = None
    """String to count"""


@dataclass
class KitchenSinkServiceComplexArgComplexResultInlineOutput:
    """Output type"""

    characterCount: Optional[int] = None
    """Count of characters"""


@dataclass
class SharedObject:
    someField: Optional[int] = None


@dataclass
class ComplexInput:
    selfRef: Optional['ComplexInput'] = None
    someSharedObj: Optional[SharedObject] = None


@dataclass
class ComplexOutput:
    selfRef: Optional['ComplexOutput'] = None
    someSharedObj: Optional[SharedObject] = None


@dataclass
class StrangeItem:
    someField: Optional[int] = None


@dataclass
class PurpleStrangeItem:
    someField: Optional[int] = None


@dataclass
class DateInput:
    date: Optional[datetime] = None
    dateTime: Optional[datetime] = None
    time: Optional[datetime] = None


@service
class KitchenSinkService:
    """A service for all types of operations"""

    scalar_arg_scalar_result: Operation[str, int] = Operation(name="scalarArgScalarResult")
    """Counts the characters in the string"""

    complex_arg_complex_result_inline: Operation[KitchenSinkServiceComplexArgComplexResultInlineInput, KitchenSinkServiceComplexArgComplexResultInlineOutput] = Operation(name="complexArgComplexResultInline")
    """Counts the characters in a string"""

    scalar_arg_scalar_result_external: Operation[str, int] = Operation(name="scalarArgScalarResultExternal")

    complex_arg_complex_result_external: Operation[ComplexInput, ComplexOutput] = Operation(name="complexArgComplexResultExternal")


@service(name="Strange{Item}")
class StrangeItemService:
    strange_item: Operation[StrangeItem, PurpleStrangeItem] = Operation(name="Strange{Item}")

    strange_item2: Operation[None, None] = Operation(name="StrangeItem")


@service(name="StrangeItem")
class StrangeItemService2:
    pass


@service
class ReservedWordService:
    to_string: Operation[None, None] = Operation(name="ToString")


@service
class ExistingTypesService:
    specific_types_for_some_langs: Operation[services.types.MyExistingType, ComplexOutput] = Operation(name="specificTypesForSomeLangs")

    specific_types_for_other_langs: Operation[ComplexInput, collections.deque] = Operation(name="specificTypesForOtherLangs")


@service
class DateService:
    date_operation: Operation[DateInput, None] = Operation(name="dateOperation")
