# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from nexusrpc import service, Operation
import collections
import services.types


class KitchenSinkServiceComplexArgComplexResultInlineInput(BaseModel):
    """Input type"""

    string: Optional[str] = None
    """String to count"""


class KitchenSinkServiceComplexArgComplexResultInlineOutput(BaseModel):
    """Output type"""

    character_count: Optional[int] = Field(None, serialization_alias="characterCount")
    """Count of characters"""


class SharedObject(BaseModel):
    some_field: Optional[int] = Field(None, serialization_alias="someField")


class ComplexInput(BaseModel):
    self_ref: Optional["ComplexInput"] = Field(None, serialization_alias="selfRef")
    some_shared_obj: Optional[SharedObject] = Field(
        None, serialization_alias="someSharedObj"
    )


class ComplexOutput(BaseModel):
    self_ref: Optional["ComplexOutput"] = Field(None, serialization_alias="selfRef")
    some_shared_obj: Optional[SharedObject] = Field(
        None, serialization_alias="someSharedObj"
    )


class StrangeItem(BaseModel):
    some_field: Optional[int] = Field(None, serialization_alias="someField")


class PurpleStrangeItem(BaseModel):
    some_field: Optional[int] = Field(None, serialization_alias="someField")


class DateInput(BaseModel):
    date: Optional[datetime] = None
    date_time: Optional[datetime] = Field(None, serialization_alias="dateTime")
    time: Optional[datetime] = None


@service
class KitchenSinkService:
    """A service for all types of operations"""

    scalar_arg_scalar_result: Operation[str, int] = Operation(
        name="scalarArgScalarResult"
    )
    """Counts the characters in the string"""

    complex_arg_complex_result_inline: Operation[
        KitchenSinkServiceComplexArgComplexResultInlineInput,
        KitchenSinkServiceComplexArgComplexResultInlineOutput,
    ] = Operation(name="complexArgComplexResultInline")
    """Counts the characters in a string"""

    scalar_arg_scalar_result_external: Operation[str, int] = Operation(
        name="scalarArgScalarResultExternal"
    )

    complex_arg_complex_result_external: Operation[ComplexInput, ComplexOutput] = (
        Operation(name="complexArgComplexResultExternal")
    )


@service(name="Strange{Item}")
class StrangeItemService:
    strange_item: Operation[StrangeItem, PurpleStrangeItem] = Operation(
        name="Strange{Item}"
    )

    strange_item2: Operation[None, None] = Operation(name="StrangeItem")


@service(name="StrangeItem")
class StrangeItemService2:
    pass


@service
class ReservedWordService:
    to_string: Operation[None, None] = Operation(name="ToString")


@service
class ExistingTypesService:
    specific_types_for_some_langs: Operation[
        services.types.MyExistingType, ComplexOutput
    ] = Operation(name="specificTypesForSomeLangs")

    specific_types_for_other_langs: Operation[ComplexInput, collections.deque] = (
        Operation(name="specificTypesForOtherLangs")
    )


@service
class DateService:
    date_operation: Operation[DateInput, None] = Operation(name="dateOperation")
