// <auto-generated />
#pragma warning disable CS8618

namespace NexusServices
{
    using NexusRpc;
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    /// <summary>
    /// A service for managing users.
    /// </summary>
    [NexusService]
    public interface IUserService
    {
        /// <summary>
        /// Get a user.
        /// </summary>
        [NexusOperation("getUser")]
        GetUserOutput GetUser(GetUserInput input);

        /// <summary>
        /// Create or update a user.
        /// </summary>
        [NexusOperation("setUser")]
        SetUserOutput SetUser(SetUserInput input);

        /// <summary>
        /// Delete a user.
        /// </summary>
        [NexusOperation("deleteUser")]
        void DeleteUser(DeleteUserInput input);
    }

    public partial class GetUserInput
    {
        /// <summary>
        /// User ID for the user.
        /// </summary>
        [JsonPropertyName("userId")]
        public string UserId { get; set; }
    }

    public partial class GetUserOutput
    {
        [JsonPropertyName("user")]
        public User User { get; set; }
    }

    /// <summary>
    /// A user.
    /// </summary>
    public partial class User
    {
        /// <summary>
        /// Email for the user.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// User ID for the user.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("userId")]
        public string UserId { get; set; }
    }

    public partial class SetUserInput
    {
        [JsonPropertyName("user")]
        public User User { get; set; }
    }

    public partial class SetUserOutput
    {
        [JsonPropertyName("user")]
        public User User { get; set; }
    }

    public partial class DeleteUserInput
    {
        /// <summary>
        /// User ID for the user.
        /// </summary>
        [JsonPropertyName("userId")]
        public string UserId { get; set; }
    }
}
