// Code generated by nexus-rpc-gen. DO NOT EDIT.

package main

import "github.com/nexus-rpc/sdk-go/nexus"

// A service for managing users.
var UserService = struct {
	ServiceName                string
	// Get a user.             
	GetUser                    nexus.OperationReference[GetUserInput, GetUserOutput]
	// Create or update a user.
	SetUser                    nexus.OperationReference[SetUserInput, SetUserOutput]
	// Delete a user.          
	DeleteUser                 nexus.OperationReference[DeleteUserInput, nexus.NoValue]
}{
	ServiceName: "UserService",
	GetUser:     nexus.NewOperationReference[GetUserInput, GetUserOutput]("getUser"),
	SetUser:     nexus.NewOperationReference[SetUserInput, SetUserOutput]("setUser"),
	DeleteUser:  nexus.NewOperationReference[DeleteUserInput, nexus.NoValue]("deleteUser"),
}

type GetUserInput struct {
	// User ID for the user.       
	UserID                  string `json:"userId"`
}

type GetUserOutput struct {
	User User `json:"user"`
}

// A user.
type User struct {
	// Email for the user.         
	Email                   string `json:"email,omitempty"`
	// User ID for the user.       
	UserID                  string `json:"userId,omitempty"`
}

type SetUserInput struct {
	User User `json:"user"`
}

type SetUserOutput struct {
	User User `json:"user"`
}

type DeleteUserInput struct {
	// User ID for the user.       
	UserID                  string `json:"userId"`
}
