// Generated by nexus-rpc-gen. DO NOT EDIT!

import * as nexus from "nexus-rpc";

/**
 * Exercises a broad set of JSON Schema features.
 */
export const jsonSchemaFeaturesService = nexus.service(
  "JsonSchemaFeaturesService",
  {
    roundTrip: nexus.operation<
      JSONSchemaFeaturesPayload,
      JSONSchemaFeaturesPayload
    >(),
  },
);

/**
 * A payload intended to exercise many JSON Schema features.
 */
export interface JSONSchemaFeaturesPayload {
  active: boolean;
  address: ShippingAddress;
  contact: PrimaryContact;
  count: number;
  fixedKind: FixedKind;
  history: HistoryEvent[];
  id: string;
  manager: Manager;
  metadata: { [key: string]: string };
  nullableNote: null | string;
  pet: Cat;
  price: number;
  scoreMatrix: Array<number[]>;
  status: Status;
  tags: string[];
  timestamp: string;
  variant: number | string;
}

export interface ShippingAddress {
  city: string;
  countryCode: string;
  line1: string;
  postalCode?: string;
  instructions?: string;
  residential: boolean;
  [property: string]: any;
}

export interface PrimaryContact {
  email: string;
  method: Method;
}

export enum Method {
  Email = "email",
}

export enum FixedKind {
  Payload = "payload",
}

export interface HistoryEvent {
  action: Action;
  actor: number | string;
  at: string;
}

export enum Action {
  Created = "created",
  Updated = "updated",
}

export interface Manager {
  email: string;
  name: string;
  department: string;
  reports?: number;
  [property: string]: any;
}

export interface Cat {
  hunts?: boolean;
  kind: Kind;
  breed?: Breed;
}

export enum Breed {
  Herding = "herding",
  Hound = "hound",
  Working = "working",
}

export enum Kind {
  Cat = "cat",
  Dog = "dog",
}

export enum Status {
  Active = "active",
  Disabled = "disabled",
  Pending = "pending",
}
