# Generated by nexus-rpc-gen. DO NOT EDIT!

from __future__ import annotations

from pydantic import BaseModel, Field
from nexusrpc import service, Operation
import inventory.types


class AddItemInput(BaseModel):
    initial_quantity: int = Field(..., serialization_alias="initialQuantity")
    """Starting quantity to stock."""

    name: str
    """Human-readable item name."""

    sku: str
    """Stock-keeping unit identifier."""


class AddItemOutput(BaseModel):
    added: bool
    """Whether the item was successfully added."""


class GetItemStockInput(BaseModel):
    sku: str
    """The SKU to look up."""


class ReserveStockInput(BaseModel):
    order_id: str = Field(..., serialization_alias="orderId")
    """The order this reservation is for."""

    quantity: int
    """Number of units to reserve."""

    sku: str
    """The SKU to reserve."""


class ReserveStockOutput(BaseModel):
    reserved: bool
    """Whether the stock was successfully reserved."""


@service
class InventoryService:
    """An inventory tracking service that demonstrates using $langRef to reference types that
    already exist in your target language instead of generating new ones.
    """
    add_item: Operation[AddItemInput, AddItemOutput] = Operation(name="addItem")
    """Add a new item to the inventory."""

    get_item_stock: Operation[GetItemStockInput, inventory.types.StockLevel] = Operation(name="getItemStock")
    """Get current stock levels for an item."""

    reserve_stock: Operation[ReserveStockInput, ReserveStockOutput] = Operation(name="reserveStock")
    """Reserve stock for a pending order."""
