// Code generated by nexus-rpc-gen. DO NOT EDIT.

package services

import "time"

import "github.com/nexus-rpc/sdk-go/nexus"

// Exercises a broad set of JSON Schema features.
var JSONSchemaFeaturesService = struct {
	ServiceName string
	RoundTrip   nexus.OperationReference[JSONSchemaFeaturesPayload, JSONSchemaFeaturesPayload]
}{
	ServiceName: "JsonSchemaFeaturesService",
	RoundTrip:   nexus.NewOperationReference[JSONSchemaFeaturesPayload, JSONSchemaFeaturesPayload]("roundTrip"),
}

// A payload intended to exercise many JSON Schema features.
type JSONSchemaFeaturesPayload struct {
	Active       bool              `json:"active"`
	Address      ShippingAddress   `json:"address"`
	Contact      PrimaryContact    `json:"contact"`
	Count        int64             `json:"count"`
	FixedKind    FixedKind         `json:"fixedKind"`
	History      []HistoryEvent    `json:"history"`
	ID           string            `json:"id"`
	Manager      Manager           `json:"manager"`
	Metadata     map[string]string `json:"metadata"`
	NullableNote string            `json:"nullableNote"`
	Pet          PetClass          `json:"pet"`
	Price        float64           `json:"price"`
	ScoreMatrix  [][]float64       `json:"scoreMatrix"`
	Status       Status            `json:"status"`
	Tags         []string          `json:"tags"`
	Timestamp    time.Time         `json:"timestamp"`
	Variant      *Actor            `json:"variant"`
}

type ShippingAddress struct {
	City         string `json:"city"`
	CountryCode  string `json:"countryCode"`
	Line1        string `json:"line1"`
	PostalCode   string `json:"postalCode,omitempty"`
	Instructions string `json:"instructions,omitempty"`
	Residential  bool   `json:"residential"`
}

type PrimaryContact struct {
	Email  string `json:"email"`
	Method Method `json:"method"`
}

type HistoryEvent struct {
	Action Action    `json:"action"`
	Actor  *Actor    `json:"actor"`
	At     time.Time `json:"at"`
}

type Manager struct {
	Email      string `json:"email"`
	Name       string `json:"name"`
	Department string `json:"department"`
	Reports    int64  `json:"reports,omitempty"`
}

type PetClass struct {
	Hunts bool   `json:"hunts,omitempty"`
	Kind  Kind   `json:"kind"`
	Breed *Breed `json:"breed,omitempty"`
}

type Method string

const (
	Email Method = "email"
)

type FixedKind string

const (
	Payload FixedKind = "payload"
)

type Action string

const (
	Created Action = "created"
	Updated Action = "updated"
)

type Breed string

const (
	Herding Breed = "herding"
	Hound   Breed = "hound"
	Working Breed = "working"
)

type Kind string

const (
	Cat Kind = "cat"
	Dog Kind = "dog"
)

type Status string

const (
	Active   Status = "active"
	Disabled Status = "disabled"
	Pending  Status = "pending"
)

type Actor struct {
	Integer int64
	String  string
}
